### ISSUE TITLE
Don't use hello.ipn.dev to check up status

### ISSUE THREAD

**Issue by rosszurowski** [tailscale/github-action#11]
As of a few weeks ago, we no longer add hello.ipn.dev to new networks. If we're relying on these lines to successfully run the action, many new users may run into issues, along with existing users who have removed hello from their network.

https://github.com/tailscale/github-action/blob/cc6818dd6930277a6e4b5d249e32ba2f4cf6ea32/.github/workflows/tailscale.yml#L23-L25

**Comment by DentonGentry** [comment]
It isn't obvious, but:
- the YML file that users of this Action use is https://github.com/tailscale/github-action/blob/main/action.yml, which has no mention of hello.ipn.dev
- https://github.com/tailscale/github-action/blob/main/.github/workflows/tailscale.yml is for us, to test the Action when updating the Tailscale version. It does reference hello.ipn.dev for this test. We could remove this by starting a node on the same Tailnet with it, I just didn't really want to leave a droplet or something running all the time for it.

**Comment by rosszurowski** [comment]
Ah, that makes more sense. I was surprised by that YAML file, but the fact that it uses `action.yml` rather than something in the workflows folder seems reasonable. Thanks!
