### ISSUE TITLE
Outdated credential information + version

### ISSUE THREAD

**Issue by sebastianarena** [tailscale/github-action#143]
Hello,
With the current fine-grained controls, I cannot seem to setup a proper credential for this to run. I can only do it if I allow complete access, but the old "devices" settings is now "devices:core" and it no longer works with just that.
Also, for some reason, if not specified, the action uses a version 1.42 instead of the most updated one. Shouldn't it use the latest available version via default?
Thanks!

**Comment by daankets** [comment]
Same issue here

**Comment by tendstofortytwo** [comment]
Hi! You don't need `devices:core`, you need `auth_keys`.
