### ISSUE TITLE
Suddenly hangs until timeout waiting on http://local-tailscaled.sock/localapi/v0/status

### ISSUE THREAD

**Issue by bithavoc** [tailscale/github-action#15]
I've been running this github action for months until somewhat recently(last few weeks) it started hanging indefinitely until it timeouts:

Step configuration:

```
      - uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
```

`TAILSCALE_AUTHKEY` secret is correctly set in the repository secrets(unlike previously reported in #8), in fact, this secret has not been changed since I first started using this action.

Here's the log output:
```
Run tailscale/github-action@main
Run MINOR=$(echo "$VERSION" | awk -F '.' {'print $2'})
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 14.2M  100 14.2M    0     0  13.6M      0  0:00:01  0:00:01 --:--:-- 13.6M
Run sudo tailscaled 2>~/tailscaled.log &
failed to connect to local tailscaled (which appears to be running). Got error: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
```

**Comment by DentonGentry** [comment]
> TAILSCALE_AUTHKEY secret is correctly set in the repository secrets(unlike previously reported in #8), in fact, this secret has not been changed since I first started using this action.

I suspect that is the issue: authkeys expire after 90 days, after which they will no longer authorize new nodes. Creating a new ephemeral authkey at https://login.tailscale.com/admin/settings/authkeys and putting the new one in TAILSCALE_AUTHKEY will likely resolve the issue.

We're working on other ways to authorize the GitHub Action runner that won't require a new authkey every 90 days, but nothing is ready quite yet.

**Comment by bithavoc** [comment]
@DentonGentry 🚀 Thank you very much, that was it, the key expired and I once I rotated it no longer timeouts. A warning message would be appreciated though.

**Note:** I'm not encouraging you to work on Saturdays but damn that was cool, Tailscale does not disappoint.
