### ISSUE TITLE
Upgrade to 1.16.0 and remove the sleep retry loop?

### ISSUE THREAD

**Issue by bradfitz** [tailscale/github-action#17]
Time to upgrade to 1.16.0 and remove the sleep retry loop?

/cc @DentonGentry

**Comment by DentonGentry** [comment]
Yes, here and in the various serverless KB articles. This probably won't be done today, but soon.

**Comment by DentonGentry** [comment]
Fixed by https://github.com/tailscale/github-action/pull/21
