### ISSUE TITLE
notice when TAILSCALE_AUTHKEY is missing, and error early

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/github-action#19]
When a pull request is initiated from a fork, none of the secrets of the original repo are available. This notably includes the TAILSCALE_AUTHKEY, which means tailscaled in the CI runner is trying to start with "tailscale up --authkey= --hostname=name"

We should notice if the authkey is empty and exit early with a comprehensible error message.

**Comment by tendstofortytwo** [comment]
It would be nice if you could also detect an expired authkey. :) Not sure if worth making a separate issue for that?

**Comment by willnorris** [comment]
perhaps related, but we recently had an issue where an auth key was accidentally revoked (https://github.com/tailscale/corp/issues/7280).  The behavior there was that the tailscale action hung and was eventually killed by GitHub after ~6 hours.  Like the above cases, this seems like something we should be able to detect and fail fast.
