### ISSUE TITLE
Feature request: run tailscale logout automatically at the end of a job

### ISSUE THREAD

**Issue by tavianator** [tailscale/github-action#2]
It would be nice to run `tailscale logout` after the job, since even ephemeral machines stick around in the admin UI for a day or two.  Unfortunately composite actions don't support "post-job steps," but JavaScript actions do: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#post.

**Comment by DentonGentry** [comment]
Though ephemeral nodes initially were deleted 48 hours after becoming inactive, a few weeks ago we reduced it to one hour before deletion. Is that sufficient for this?

**Comment by tavianator** [comment]
That's probably fine.  I made this issue after seeing https://twitter.com/apenwarr/status/1394794106417733634, before I realized that `tailscale logout` [doesn't actually hide the machine from the panel anyway](https://twitter.com/apenwarr/status/1395054293833637894).
