### ISSUE TITLE
dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory

### ISSUE THREAD

**Issue by tavianator** [tailscale/github-action#22]
Recently I started getting this error in my Tailscale action: https://github.com/tavianator/bfs/runs/4326330477

>     can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory

I believe it's a race between `sudo tailscaled 2>~/tailscaled.log &` and `sudo tailscale up`.  The daemon hasn't finished creating the socket by the time `tailscale up` runs, which fails immediately.  Since #21 there's no retry so it gives up.

Previous successful runs show the same error message, followed by success: https://github.com/tavianator/bfs/runs/4243383466

**Comment by bradfitz** [comment]
I don't know GitHub Actions, but are you pinning version 1.8.3? That's a very old Tailscale version (if that's how I'm reading it) that predates the automatic retry loop.

/cc @DentonGentry

**Comment by tavianator** [comment]
Oh whoops, I forgot I was doing that.  Looks like that fixed it: https://github.com/tavianator/bfs/actions/runs/1504678382
