### ISSUE TITLE
Create release for 1.18?

### ISSUE THREAD

**Issue by dave-andersen** [tailscale/github-action#23]
Hi, TS folks - the bug that was fixed by this commit:

https://github.com/tailscale/github-action/commit/d1256d457746f421e7cd4c5e5855a6bce058eb24#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6

just bit us, causing a github worker to spin for 8 hours until we noticed it. 😂 Our workers didn't auto-grab the new version because there wasn't a new release.

Would it be possible to tag a new Release that incorporates the update to 1.18 and loop fix?

Thanks!

**Comment by bradfitz** [comment]
cc @DentonGentry @maisem

**Comment by jazzdan** [comment]
Would also be helpful for the new `args` feature added in b10fe7b66939938d10e203f6ae07776a5d135d08 :)

**Comment by bxb100** [comment]
You can temporary using the commit id to use latest version
`uses: tailscale/github-action@ecdb6a2aed7b74d1c8ec0c78fbd76a84b9809b28`

**Comment by dagheyman** [comment]
+1, was very confusing to try this action out and have the action spin forever :)

**Comment by DentonGentry** [comment]
`main` is currently on 1.24.
