### ISSUE TITLE
Auth keys are printed to stdout

### ISSUE THREAD

**Issue by uhthomas** [tailscale/github-action#42]
It seems as if auth keys are printed plainly to stdout in some circumstances. I'm surprised GitHub isn't redacting this automatically, but I also don't think Tailscale should be printing auth keys like this.

```
backend error: invalid key: API key k6e7bE3CNTRL not valid
```

See: https://github.com/uhthomas/automata/runs/7373878755?check_suite_focus=true#step%3A3%3A36=

I understand the API key is "invalid", but it was once valid.

**Comment by maisem** [comment]
That's just the Key ID. The secret part seems to be redacted.

**Comment by uhthomas** [comment]
Ah, I see now. Thanks!
