### ISSUE TITLE
tailscale/github-action@v1 is old

### ISSUE THREAD

**Issue by milkcocoa** [tailscale/github-action#44]
I use this action with `@v1` as follows.

```
- uses: tailscale/github-action@v1
  with:
    authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
```

GitHub actions runner seems to use the old tailscale 1.14 version.
Is this behavior intended?

**Comment by DentonGentry** [comment]
We applied the v1 tag to a rev which used 1.14. You can set a `version` input argument to control the Tailscale app version to use, if desired.

**Comment by milkcocoa** [comment]
Thanks. So, you don't have any plan to release minor versions to update the tailsscale version, right?

**Comment by DentonGentry** [comment]
It just seemed superfluous to add a v2, v3, v4, etc.
- If you want to automatically get new versions of the client periodically, don't specify a tag or hash at all and you'll get whatever `main` updates to.
- If you tie it to `v1` or to a git hash, you'll get that version of the github action forever.
- If you want to control the Tailscale client version used and don't want to let the action use `main`, then pass in a version argument to specify the client version to use.

**Comment by milkcocoa** [comment]
Thanks, but I'm talking about the `minor` version instead of the `major` version, so when v1.0.1 or v1.1 is released with the latest version of tailscale, I can automatically track it with `@v1`.

**Comment by AlekSi** [comment]
As funny as it sounds, GitHub recommends moving git tags for new releases. From https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management
> Move the major version tag (such as v1, v2) to point to the Git ref of the current release. 

I would prefer this action to behave like other actions, even if it is not how git tags should be used “normally”.

**Comment by DentonGentry** [comment]
We are working on implementing [OAuth client support](https://tailscale.com/kb/1215/oauth-clients/) in the action, which will be a v2 tag.

**Comment by milkcocoa** [comment]
Hmm, as my English is likely to be poor, there might be misunderstanding, but I was not talking about the major version releases in this thread.

**Comment by AlekSi** [comment]
> If you tie it to v1 or to a git hash, you'll get that version of the github action forever

What I tried to say is that this is not how GitHub Actions typically work. If one uses `actions/checkout@v3`, they will not get that version of the action forever. Instead, they will get the latest v3.y.z. And this is achived my moving git tag: https://github.com/actions/checkout/tags – note that currently v3 and v3.3.0 point to the same commit, but v3.2.0 and older tags are still there.
