### ISSUE TITLE
hangs with expired authkey

### ISSUE THREAD

**Issue by markmartirosian** [tailscale/github-action#50]
Tailscale actions hangs for hours if the authkey is expired. Most probably waiting for interactive cli auth flow.

**Comment by reinismu** [comment]
Noticed the same issue.

Also a bit sad that I have to go and manually change all auth keys for all of my projects every 90 days...

**Comment by willnorris** [comment]
added timeout in the action, but you can also specify one in your workflow config.  The action also now supports OAuth clients, which don't need to be rotated every 90 days.
