### ISSUE TITLE
Tailscale needs to be installed first?

### ISSUE THREAD

**Issue by selfagency** [tailscale/github-action#55]
On my first attempt at running this action, I got the error:

```
failed to connect to local tailscaled; it doesn't appear to be running (sudo systemctl start tailscaled ?)
```

So I added a step:

```
- name: Add dependencies
  run: |
    curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.gpg | sudo apt-key add -
    curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.list | sudo tee /etc/apt/sources.list.d/tailscale.list
    sudo apt update -y
    sudo apt install tailscale -y
```

And then it worked but, the instructions don't say that that's necessary. Generally, your action should install Tailscale itself if it isn't already.

**Comment by DentonGentry** [comment]
Installing the binaries happens here: https://github.com/tailscale/github-action/blob/ce41a99162202a647a4b24c30c558a567b926709/action.yml#L40

Is there something unusual about the runner, like is it self-hosted? Is it ARM? Looking at the code in action.yml, it does assume x86_64.

**Comment by selfagency** [comment]
I switched from using `@v1` to `@main` and now it works.
