### ISSUE TITLE
Feature Request: Advertise ACL Tags

### ISSUE THREAD

**Issue by smkjason** [tailscale/github-action#58]
I'd love to be able to configure ACL tags to the GitHub runner machines with the `tailscale up` command by adding the flag `--advertise-tags`. 

There would be an optional input specifying the tags you want to advertise. 

Ref: https://tailscale.com/kb/1068/acl-tags/#applying-a-tag-to-a-device-with-the-cli

**Comment by DentonGentry** [comment]
At this point we'd generally advise adding the tags to the authkey: https://tailscale.com/kb/1068/acl-tags/#using-an-acl-tag-with-an-auth-key
Is there a reason the CLI would be preferred?

To use the CLI one could set the environment variable: `ADDITIONAL_ARGS="--advertise-tags=tag1,tag2"`

**Comment by smkjason** [comment]
@DentonGentry Apologies, I actually missed that part. Thanks for the direction!
