### ISSUE TITLE
Will the releases be updated to v2?

### ISSUE THREAD

**Issue by andrewgbell** [tailscale/github-action#76]
Hi, I noticed there's be some recent changes to master including the use of oauth.  Seems to work well and wondered if the releases will be updated from v1 to v2, as the readme.md currently uses v2 (which doesn't seem to exist)?

    uses: tailscale/github-action@v2

But v1 here.
https://github.com/tailscale/github-action/releases

As an aside, is there any plans for us to be able to choose latest as a version to install, e.g.

    - uses: tailscale/github-action@main
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
           version: latest

**Comment by DentonGentry** [comment]
We submitted the OAuth code last night, applying the v2 tag and [a changelog notification](https://tailscale.com/changelog/) is intended for today.

> As an aside, is there any plans for us to be able to choose latest as a version to install, e.g.

The tradeoff we face is:
- most new Tailscale features like SSH or audit logs or so forth don't really benefit the narrow niche of CI runners
- literally every time we update the client version in this github-action, we get a burst of problem reports attributing every problem with GitHub to the new Tailscale version

So we settled into a cadence where we skip a few Tailscale releases between updates of the Action. We maintain backwards compatibility with prior Tailscale versions for a very, very long time (we still support the few remaining nodes running version 0.9.0), so CI runners a few versions back will interoperate with the rest of the tailnet a few versions forward.

**Comment by andrewgbell** [comment]
That's great thanks.  I'd seen a few updates to main over the months so wasn't sure whether to follow main on the action or the versions.  I like to live dangerously...

I get your point on the trade-offs.  I imagine the downtime currently happening with GitHub now will be attributed to your release!  But appreciate the answer, and makes sense.  If it's being updated gradually then I'm all good with that.

**Comment by DentonGentry** [comment]
The `v2` tag has been pushed and [the ChangeLog published](https://tailscale.com/changelog/#2023-06-29-service).
