### ISSUE TITLE
Hangs when connecting tailscale

### ISSUE THREAD

**Issue by offbyone** [tailscale/github-action#99]
I have this action run that should be setting up tailscale:

https://github.com/ChicagoWorldcon/infrastructure/actions/runs/7065526605/job/19235706210

I have configured my OAuth client and provided that as organization secrets, and wired them in to that workflow.

I can see the machines being created and appearing in my tailscale admin, but the command never returns

The logs for old runs don't appear to allow the tailscale section to expand, but here's what they look like: 

<img width="1106" alt="image" src="https://github.com/tailscale/github-action/assets/181693/3e14d716-5961-4063-a7b8-aa51ae3adf23">

**Comment by offbyone** [comment]
I've done a bit further investigation here; tailscale itself seems to be running fine, but what _isn't_ is that all outbound network connectivity on the actions runner seems to have stopped functioning completely as soon as I set up an exit node. If I leave the exit node off, then the whole purpose of this addition isn't working -- I need an exit node so that the action can use a static IP to talk to an API that requires me to manually add client IP address -- but that feature seems to break all _other_ GitHub actions.

**Comment by DentonGentry** [comment]
I don't have a way to know what tailnet this is, but one possibility is that the ACLs do not allow the tag being used for the GitHub action to access `autogroup:internet`

If you can generate a `tailscale bugreport` from any other node on the tailnet, we can use it to look up the account. Alternately you can [contact support](https://tailscale.com/contact/support/) and reference https://github.com/tailscale/github-action/issues/99

**Comment by offbyone** [comment]
That was, in fact, the issue; I had set the ACL to allow access to the bastion node, but not to the autogroup.

Sorry, folks; PEBKAC here.
